### ISSUE TITLE
数字数组中为0的元素为nil

### ISSUE THREAD

**Issue by feng743** [waizui/EasyLua#2]
数字数组中为0的元素无法正常赋值

**Comment by feng743** [comment]
目前定位到的是在 DrawNumber 函数中，首次绘制的值为0，EasyLuaParam 获取到的的值也是0，导致不会去触发 Set 从而无法设置 EasyLuaParamType

**Comment by waizui** [comment]
> 数字数组中为0的元素无法正常赋值

有没有更具体的说明，我在编辑器内先对数字数组的元素赋值0，后面也可以改为其它值，没有复现你说的问题。

**Comment by feng743** [comment]
> > 数字数组中为0的元素无法正常赋值
> 
> 有没有更具体的说明，我在编辑器内先对数字数组的元素赋值0，后面也可以改为其它值，没有复现你说的问题。

声明数组后在编辑器中只设置长度，返回脚本获取数组中的元素，获取到的就是nil

**Comment by waizui** [comment]
fixed @feng743 [816fc6a](https://github.com/waizui/EasyLua/commit/816fc6ac2d0eee939e0a881392201c08913526fc)
